### ISSUE TITLE
GetObjects not Defined?

### ISSUE THREAD

**Issue by CaptainCharles** [appductionstudios/corona_parse_wrapper#1]
Hi.  I'm trying to use this to modify an existing Parse.com project to use Parse-Server, but I'm getting  an error from my "GetObjects" calls:

attempt to call method 'getObjects' (a nil value)

It seems the getObjects function wasn't defined in Parse_Wrapper.  The Parse_Mod file has a getObjects call, which we've been using extensively.  I think we might have been using a different version of Mod_Parse.  Could you please tell us what function we should be using to get objects using Parse-Wrapper?

**Comment by majidhassan** [comment]
Hey Charles,

The getObjects function is not implemented yet. You could add it and create a pull request, or - if you prefer - you could wait a bit till we update the wrapper with getObjects.

**Comment by CaptainCharles** [comment]
Thank you. I'll just check back later, then.
